// Hand-written declarations for plain extern "C" Rust functions that are NOT
// generated by swift-bridge (so they won't appear in jarvis_ios.h).
#pragma once
#include <stdint.h>

/// Install the crash-log file writer and tracing subscriber.
/// Call once before `jarvis_renderer_new`.
///   log_path  – path to write this session's log (created/appended)
///   prev_path – informational: path where Swift already moved the previous session log
void jarvis_ios_set_log_file(const char* log_path, const char* prev_path);
