// File automatically generated by swift-bridge.
#include <stdint.h>
void* __swift_bridge__$jarvis_ios_version(void);
uint8_t* __swift_bridge__$jarvis_renderer_new(uint8_t* ui_view, uint32_t width_px, uint32_t height_px, float pixels_per_point);
void __swift_bridge__$jarvis_renderer_free(uint8_t* ptr);
void __swift_bridge__$jarvis_renderer_render(uint8_t* ptr, double time_seconds);
void __swift_bridge__$jarvis_renderer_resize(uint8_t* ptr, uint32_t width_px, uint32_t height_px);
void __swift_bridge__$jarvis_renderer_touch(uint8_t* ptr, uint8_t phase, float x, float y, uint64_t id);
void __swift_bridge__$jarvis_renderer_reload_profile(uint8_t* ptr);
void __swift_bridge__$jarvis_renderer_queue_vrma(uint8_t* ptr, uint8_t const * path_ptr, uintptr_t path_len, uint8_t loop_forever);
void* __swift_bridge__$jarvis_ios_debug_log_snapshot(void);
void __swift_bridge__$jarvis_ios_debug_log_clear(void);


