//! Bevy plugins (binary crate).

pub mod avatar;
pub mod debug_ui;
pub mod environment;
pub mod expressions;
pub mod look_at;
pub mod orbit_camera;
mod vrm_eye_debug;
pub use vrm_eye_debug::VrmEyeLookatDebug;
pub mod anim_layer_sets;
pub mod anim_layers;
pub mod channel_server;
pub mod chat_pipeline_status;
pub mod emotion_map;
pub mod graphics_advanced;
pub mod ha_vision_gaze;
pub mod home_assistant;
pub mod home_assistant_events;
pub mod home_assistant_routing;
pub mod hub_pose_apply;
pub mod idle_tick;
pub mod ironclaw_chat;
mod jarvis_ios_hub;
pub mod light_rig;
pub mod mtoon_overrides;
pub mod native_anim_player;
pub mod pose_capture;
pub mod pose_driver;
pub mod pose_library_assets;
pub mod rig_editor;
pub mod service_status;
pub mod shared_runtime;
pub mod spring_bone;
mod spring_preset;
pub mod traffic_log;
pub mod tts;
